### ISSUE TITLE
Triangular notation somehow gets stuck formatting `(e^1.378e163)1`

### ISSUE THREAD

**Issue by James103** [MathCookie17/Eternal-Notations#5]
When formatting `(e^1.378e163)1`, the Triangular notation gets stuck in the following while loop:
https://github.com/MathCookie17/Eternal-Notations/blob/d245243824804d59b9ab41271b6eb2b3b8d6a4a9/dist/eternal_notations.js#L1775-L1780

The notation also gets stuck in the same way for `(e^1.000001e100)1`, but not for `(e^1e100)1`.

This may also affect the Square notation.

Stack trace:
```
triPolygonRoot (https://mathcookie17.github.io/Eternal-Notations/dist/eternal_notations.js#1776)
formatDecimal (https://mathcookie17.github.io/Eternal-Notations/dist/eternal_notations.js#9954)
format (https://mathcookie17.github.io/Eternal-Notations/dist/eternal_notations.js#1823)
formatOne (https://mathcookie17.github.io/Eternal-Notations/webpage.js#81)
formatAll (https://mathcookie17.github.io/Eternal-Notations/webpage.js#47)
(global) (source-actor-server0.conn0.windowGlobal773094113281/source62#1)
```

**Comment by MathCookie17** [comment]
This one was caused by the same thing causing those (e^9e15)1 errors: Decimals stop being integer-precise at 9e15, so slog can run into imprecision errors when a notation uses it to measure how many layers to cut down a number by, which many notations do. I wouldn't be surprised if there are yet more of these errors... so if you want to continue your crusade against Eternal Notations errors (which you've been doing a good job of so far), numbers above (e^9e15) are a good place to search.

Seriously, though, how do you keep finding these? Like, I get how you found #2, but this one in particular seems like it would have been hard to find.
